export interface TrainingStep {
  step: number;
  title: string;
  en: string;
  zu: string;
  xh: string;
  st: string;
}

export interface TrainingCourse {
  courseId: string;
  title: string;
  steps: TrainingStep[];
}

export const FRESH_OHS_PROJECT_REGISTRY: Record<string, TrainingCourse> = {
  CORPORATE_POSTURE: {
    courseId: "ST-CP-001",
    title: "COURSE 1: CORPORATE POSTURE & WORKSTATION ENGINEERING",
    steps: [
      {
        step: 1,
        title: "ERGONOMIC ALIGNMENT",
        en: "ADJUST YOUR MONITOR HEIGHT SO THE TOP OF THE SCREEN IS AT OR SLIGHTLY BELOW EYE LEVEL. SIT AT AN ARM'S LENGTH DISTANCE (50 TO 70 CM) FROM THE DISPLAY. THIS ELIMINATES CHRONIC CERVICAL SPINE STRAIN AND RESTRICTS MSD LIABILITY.",
        zu: "LUNGISA UBUPHAKAMO BESIKRINI SAKHO UKUZE INGXENYE ENGENHLA IBE SEZINGENI LAMEHLO NOMA NGEZANSI KANCANE. HLALA BUZEKELE IBANGA LENGALO (50 KUYA KULI-70 CM) UKUZE UVIMBE UKUKHATHALA KWENTAMO.",
        xh: "HLALISELA UKUBA UBUPHAKAMO BESIKRINI SAKHO KWINDAWO EFANELEKILEYO. JONGA ISIKRINI SAKHO KUMBANE WENGALO ENYE UKUTHINTELA UXINZELELO LWENTAMO.",
        st: "LUNGISELA BOPHAGAMO BJA SEKRINI SA GAGO SE BE BOEMONG BJA MAHLOTSE. DULA GO LEKANA LE LEBOGO LE LE TEE GO THIBELA DIKOTSI TSA MOLALA."
      },
      {
        step: 2,
        title: "CHAIR SIZING & LUMBAR LOCK",
        en: "CHOOSE A CHAIR THAT SUPPORTS YOUR LUMBAR CURVE. ADJUST CHAIR HEIGHT SO YOUR FEET ARE FLAT ON THE FLOOR AND THIGHS PARALLEL TO THE GROUND. PROPER SIZING PREVENTS PELVIC TILT AND SPINAL DISCOMFORT.",
        zu: "KHETHA ISIHLALO ESISEKELA UMHLANE WAKHO ONGEZANSI. LUNGISA UBUPHAKAMO BESIHLALO UKUZE IZIPHAMBANO ZEZINYAWO ZAKHO ZIBE FLAT PHANSI FUTHI APHELELE PHANSI.",
        xh: "KHETHA ISITULO ESINIKA INKXASO KWI-LUMBAR YAKHO. LUNGISA UBUPHAKAMO BESITULO UKUZE IINYAWO ZAKHO ZIBE FLAT EMHLABENI.",
        st: "KGETHA SETULO SEO SE TLAGO GO NEA SEKHUBAMA SA GAGO SE SENYENYANE INKXASO. LUNGISELA BOPHAGAMO BJA SETULO GO NETEFATSA HORE MAOTO A DULe MABALENG."
      },
      {
        step: 3,
        title: "CHAIR SPINNING & KNEELING HAZARDS",
        en: "NEVER SPIN EXCESSIVELY OR KNEEL ON AN OFFICE CHAIR. THESE BEHAVIORS STRESS THE CHAIR PNEUMATIC CYLINDER AND BASE CASTERS, CREATING AN ACTIVE COMPONENT FAILURE HAZARD AND INCREASED RISK OF UNEXPECTED FALLS.",
        zu: "UNGALOKOTHI UZUNGEZE KAKHULU NOMA UGUQE NGAMADOLO ESIHLALWENI SEHOVISI. LOKHU KUNYAKAZA KULIMAZA I-CYLINDER NEZINDAWO ZESHLALO BESE KUDALA UBUNGOZI BESIGAMEKO SOKUWA.",
        xh: "UNGAZE UJIKILEZE KAKHULU OKANYE UGUQE NGAMADOLO ESITULWENI SE-OFISI. LOKHU KUZIPHATHA KUDALA UBUNGCIPHEKO BOKUWA NGOKUPHUTHEKILEYO.",
        st: "LE KA MOHLA O SE KE WA SHIKASHIKA KAPA WA KGUNAMA KA DITOLO SETULONG SA OFISI. BOITSHWARO BO BO KOTSI BO KA BAKA DIKOTSI TSA GO WA TSE SA LEBELELWANG."
      }
    ]
  },
  OFFICE_PRANKS: {
    courseId: "ST-OP-002",
    title: "COURSE 2: OFFICE PRANKS & KINETIC LIABILITY",
    steps: [
      {
        step: 1,
        title: "KINETIC BLINDSPOTS & UNTRACKED RISKS",
        en: "NOBODY DESIGNS SOFTWARE TO TRACK THESE HIDDEN OFFICE RISKS, YET BEHAVIORS LIKE THE CATASTROPHIC 'PULLING CHAIR AWAY' PRANK IMPOSE SEVERE KINETIC LIABILITY. EXPLICITLY BAN ALL KINETIC PRANKS TO SECURE CORPORATE SAFETY COMPLIANCE.",
        zu: "AKEKHO OBLUNGISA I-SOFTWARE YOKUTHOLA LEZI ZINGOZI EZIFINYELELEKILE. VIMBELA NGOKUPHELELE UMDLALO WOKUDONSELA ISHLALO EMUVA.",
        xh: "AKUKHO MUNTU OYILA I-SOFTWARE UKUZE ALANDELE EZI NGOZI ZE-OFISI. VALA NGOKUPHELELEYO UMDLALO WOKURHOXA ISITULO.",
        st: "HA HO MOTHO YA RERANG SOFTWARE HO TRACKA DIKOTSI TSE BE BOEMONG BJA OFISI. THIBELA KA BOTLALO PAPADI EA CHAIR-PULLING."
      },
      {
        step: 2,
        title: "TRAUMATIC BRAIN & WHEEL IMPACTS",
        en: "PULLING A CHAIR INDUCES RAPID COLLAPSE, POSING A SEVERE RISK OF A COLLEAGUE STRIKING THEIR HEAD DIRECTLY ON THE SHARP METAL OR PLASTIC WHEELS OF THE OFFICE CHAIR, INDUCING IRREVERSIBLE TRAUMATIC COGNITIVE DISABILITIES.",
        zu: "UKUDONSELA ISHLALO EMUVA KUBANGA UKUWA OKUSHESHE KAKHULU FUTHI KUNGENZA SISHAYEKE EBUCHEPHELENI NGEZINDLELA ZESHLALO NOMA AMASONDOLWANE (WHEELS).",
        xh: "UKURHOXA ISITULO KUBANGA INGOZI EYENTLOKO OKANYE YENGQONDO NGEZITHUTHI ZESITULO (WHEELS) EZENTSIMBI OKANYE IPLASTIKI.",
        st: "GO SHUTISA SETULO GO BAKA DIKOTSI TSA LOGO GO HLOKAHALA KWA MAOTO A METAL KAPA PLASTIC WHEELS AO A KA GO KOBANG."
      },
      {
        step: 3,
        title: "LEGAL LIABILITY & REPORTING",
        en: "ANY INDIVIDUAL PARTICIPATING IN KINETIC OFFICE PRANKS CAN BE HELD PERSONALLY LIABLE FOR DAMAGES UNDER COMMON LAW DELICT AND FACE STATUTORY CHARGES UNDER SECTION 14 OF THE OHS ACT FOR FAILING TO ENSURE SELF/OTHER SAFETY.",
        zu: "NOMA NGABE UBANI OBANDAKANYEKA EMIDLALWENI ENGOZI ENGCUPHENI YASEHOVISI ANGAZITHOLA EBOSHELWA IMACALA EMTHETWENI WASEKHAYA NANGAPHANSI KWESIGABA 14 SO MTHETHO WE-OHS ACT.",
        xh: "NOMA NGAPHI UMNTU OTHATHA INXAXHEBA KWIINDAWO EZINJALO ZOMDLALO OFISI UYA KUBANJWA PHANTSI KWE-OHS ACT ICANDELO LE-14.",
        st: "MOTHO OFE KAPA OFE YA NKANG KAROLO HO DINKHONO TSA MOLLWANE OFISING O TLA TLAMELLA KA MOLAO WA OHS ACT KAROLO YA 14."
      }
    ]
  }
};
