// ==========================================
// 1. FRESH OHS PROJECT REGISTRY (DATA MATRICES)
// ==========================================
export interface TrainingStep {
  step: number;
  title: string;
  en: string;
  zu: string;
  xh: string;
  st: string;
}

export interface TrainingCourse {
  courseId: string;
  title: string;
  steps: TrainingStep[];
}

export const FRESH_OHS_PROJECT_REGISTRY: Record<string, TrainingCourse> = {
  BASIC_FIRST_AID: {
    courseId: "ST-FA-001",
    title: "COURSE 1: BASIC FIRST AID (SERVICE STATIONS)",
    steps: [
      {
        step: 1,
        title: "SCENE SAFETY ASSESSMENT",
        en: "BEFORE RUNNING TO ASSIST AN INJURED TEAMMATE OR CUSTOMER ON THE FORECOURT, PAUSE AND ASSESS THE SCENE FOR ACTIVE HAZARDS. CHECK FOR RUNNING VEHICLE ENGINES, POOLED FUEL VAPORS, OR TOXIC CHEMICAL SPLASHES. ENSURE THE ENVIRONMENT IS BONE-SAFE BEFORE DISPATCHING AID SO YOU DO NOT BECOME A SECOND CASUALTY.",
        zu: "NGAPHAMBI KOKUBA UGIDIMELE UKUYOSIZA OSEBENZA NAYE NOMA IKHASIMENDE ELILIMELE ENKUNDLENI, MANA KANCANE UHLOLISISE INDAWO UKUZE UBONE IZINGCUPHE EZIKHONA. BHEKA IZINJINI ZEZIMOTO EZIVUKAYO, IMHWAMUKO KAPHETHILOLI, NOMA UKUCHITHEKA KWAMAKHEMIKHALI. QINISEKISA UKUTHI INDAWO IPHEPHILE NGAPHAMBI KOKUNIKELA USIZO LOKUQALA.",
        xh: "NGAPHAMBI KOKUBA UGIDIMELE UKUNCHEDA UMSEBENZI OKANYE UMPHAKATHI OLIMELEYO EBALENI, YIMA KANCINCI UHLOLISISE INDAWO UKUZE UBORE IZINGOPHE EZIKHOYO. JONGA IINJINI ZEZITHUTHI EZIVUKAYO, UMPHUNGA KAPHETHILOLI, OKANYE UKUCHITHEKA KWEMICHIZA. QINISEKISA UKUBA INDAWO IKHUSELEKILE NGAPHAMBI KOKUNIKA UNCEDO LOKUQALA.",
        st: "PELE O MATHELA HO THUSA MOSEBETSI-MOHO KAPA MOREKI EA TSOILENG KAPELE, EMA HANYANE U HLAHLOBOBE SEBAKA BAKENG SA DIKOTSI TSE LENG TENG. HLAHLOBA DINKHONO TSA DIKOLOI TSE SEBETSANG, MOFUTHU WA GASE, KAPA DIKHEMIKHALI TSE QHALANENG. NETEFATSA HORE SEBAKA SE BOLOKEHILI PELE O FANA KA THUSO EA PELE."
      },
      {
        step: 2,
        title: "BIOLOGICAL BARRIER PROTECTION",
        en: "OPEN THE FIRST AID APPOINTMENT KIT AND IMMEDIATELY PUT ON YOUR STERILE NITRILE SAFETY GLOVES BEFORE TOUCHING THE PATIENT. NEVER CONTACT BLOOD, FUEL CONTAMINANTS, OR BODILY FLUIDS WITH BARE SKIN—THIS STRICTLY ENFORCES ISO BIOHAZARD PROTOCOLS.",
        zu: "VULA IBHOKISI LEZOKUSIZA LOKUQALA BESE UFAKA AMAGILAVU AKHO E-NITRILE APHEPHILE NGOKUSHESHA NGAPHAMBI KOKUTHINTA ISIGULI. UNGALOKOTHI UTHINTE IGAZI, UKUCHITHEKA KAPHETHILOLI, NOMA AMANZI EMZIMBA NGEZANDLA ZE—LOKHU KUPHUSHA IMITHETHO YE-ISO BIOHAZARD.",
        xh: "VULA IBHOKISI LONCEDO LOKUQALA UZE UFAKE IIGLAVU ZAKHO ZE-NITRILE EZIKHUSELEKILEYO KWANGOKO NGAPHAMBI KOKUTHINTHA ISIGULI. UNGAZE UTHINTE IGAZI, UKUCHITHEKA KAPHETHILOLI, OKANYE ULWELO LOMZIMBA NGEZANDLA ZE—LOKHU KUNYANZELISA IMITHETHO YE-ISO BIOHAZARD.",
        st: "BULA LEBOKOSE LA THUSO EA PELE MME O RWALE DITLELAFO TSA HAO TSA NITRILE KA POTLAKO PELE O AMA MOKUDI. LE KA MOHLA O SE KE WA TSHWARA MADI, MAFURA A QHALANENG, KAPA DI-FLUID TSA MMELA KA MATSOHO A HLOBO—HONA HO TIISA MELAO YA ISO BIOHAZARD."
      },
      {
        step: 3,
        title: "HIGH-PRESSURE FUEL EYE FLUSH",
        en: "IF HIGH-PRESSURE FUEL, BATTERY ACID, OR DIESEL SPLASHES DIRECTLY INTO A WORKER'S EYES, EMERGENCY FLUSHING MUST OCCUR INSTANTLY. ROUTE THE CASUALTY IMMEDIATELY TO THE EYE-WASH STATION AND IRRIGATION THE TISSUE WITH CLEAN, RUNNING WATER CONTINUOUSLY FOR FIFTEEN TO TWENTY MINUTES TO PREVENT DEEP CHEMICAL CORROSION.",
        zu: "UMA UPHETHILOLI ONOMPHEMBO OPHAKAMILEYO, I-ACID YEBHETHERI, NOMA I-DIESEL ICHITHEKELA NGQO EMEHLWENI OMSEBENZI, UKUGEZA OKUPHUTHUMAYO KUFANELE KWENZEKE KHONA LAPHO. ISA ISIGULI ESITESHI SOKUHLANZA AMEHLO BESE UGEZA AMEHLO NGAMANZI AGELEZAYO NJALO OKUNGENANI IMIZUZU EYISHUMI NANHLANU KUYA KWENGAMASHUMI AMABILI UKUZE UVIMBE UKULIMALEKA KWEZICUBU.",
        xh: "XESHIKWENI AMAFUTHA ANOMPHAMBO OPHAKAMILEYO, I-ACID YEBHEKILE, OKANYE I-DIESEL ECHITHEKELA NGQO EMEHLWENI OMSEBENZI, UKUHLAMBA OKUNGXAMISEKILEYO KUFUNEKA KWENZEKE KWANGOKO. ISA ISIGULI KWISIKHULULO SOKUHLANZA AMEHLO UZE UHLAMBE AMEHLO NGAMANZI AGELEZAYO RHOQO UBUNCINANE IMIZUZU ELINESIHLANU KUXA KWENGAMASHUMI AMABINI UKUTHINTELA UKULIMALEKA KWESIKHUMBA.",
        st: "HAEBA MAFURA A KOTSI, ASITI YA BETRI, KAPA DISELE E QHALANEKA KA RERE DIRECTLY MAHLONG A MOSEBETSI, HO HLATSOA HOA TSHOHANYETSO HO TLAMEHA HO ETSEHA HANG-HANG. ISA MOKUDI LEFELONG LA HO HLATSOA MAHLO MME O HLATSWE MAHLO KA METSI A PHALLANG BONYANE METSOTSO E LESHOME LE METSO E MEHLANO HO ISA HO E MASHOME A MABEDI HO THIBELA KOTSI E KOTSI YA DIKHEMIKHALI."
      },
      {
        step: 4,
        title: "FORECOURT HEMORRHAGE CONTROL",
        en: "FOR SEVERE LACERATIONS OR PUNCTURES FROM MACHINERY DEFECTS, DEPLOY AN ANTISEPTIC SWAB AND PLACE A STERILE FIRST AID PAD DIRECTLY ONTO THE WOUND. APPLY FIRM, CONSTANT DOWNWARD PRESSURE UNTIL BLEEDING STOPS COMPLETELY. WRAP SECURELY WITH A CONFORMING BANDAGE, VERIFYING COUNTER-TRAUMA CIRCULATION IS MAINTAINED.",
        zu: "EZILONDENI EZINHLUKUHLUKU EZIBANGELWA EMISHININI, SEBENZISA I-ANTISEPTIC SWAB BESE UBEKA INDWANGU EHLANZEKILE (STERILE PAD) NGQO ESILONDENI. CINDENZELA NGOKUQINILE UKUZE UKOPHA KUMAME NGOKUPHELELE. BOPA NGENDWANGU YOKUBOPHA (BANDAGE) IQINILE, UQINISEKISE UKUTHI IGAZI LIYAHAMBA HNTLE.",
        xh: "EZILONDENI EZINKULU EZIBANGELWA KOOMATSHINI, SEBENZISA I-ANTISEPTIC SWAB BESE UBEKA ILAPHU ELICOCOKILEYO (STERILE PAD) NGQO ESILONDENI. CINEZELA NGOKUQNILIYO UKUZE UKOPHA KUMAME NGOKUPHELELE. BOPA NGELAPHU YOKUBOPHA (BANDAGE) IQINILE, UQINISEKISE UKUBA UMBANE WEGAZI LIYAHAMBA HNTLE.",
        st: "BAKENG SA MAQEBA A MATLA A BAKOANG KE METSHINI, SEBEDISA ANTISEPTIC SWAB MME O BEHE SETLAMO SE HLOEKILENG (STERILE PAD) HODIMA LEQEBA. TLAMELLA KA MATLA HODIMA LEQEBA HO FIHLELA MADI A THOBA KA BOTLALO. KWALELA KA CONFORMING BANDAGE HO NETEFATSA HORE MADI A TSAMAYA HANTLE."
      },
      {
        step: 5,
        title: "THERMAL & CHEMICAL BURN ISOLATION",
        en: "WHETHER DEALING WITH EXHAUST SYSTEM FRICTION THERMAL BURNS OR CORROSIVE CHEMICAL SKIN EXPLOSIONS, IMMEDIATELY SUBMERGE THE BURN ZONE UNDER GENTLE, COOL RUNNING TAP WATER FOR 10 TO 20 MINUTES. NEVER PEEL CLOTHING FUSED TO THE SKIN OR APPLY OILS AND GREASE, AS THEY LOCK CRITICAL DESTRUCTIVE HEAT WITHIN THE LIVING CELLS.",
        zu: "KUKUSHA OKUBANGELWA IZINJINI NOMA AMAKHEMIKHALI AYINGOZI, SHELA AMANZI ABANDAYO OMPOMPI ENDAWENI LEYO NGOKUSHESHA IMIZUZU EYISHUMI KUYA KWENGAMASHUMI AMABILI. UNGALOKOTHI UXHOFE IZINGUBO EZINAMATHISELE ESIKHUMBEMI NOMA USEBENZISE AMAFUTHA NEBHOTELA, NGBA LOKHU KUVALA UKUSHISA NGAPHAKATHI EZICUBU_NI.",
        xh: "KUKUTSHA OKUBANGELWA ZIINJINI OKANYE IMICHIZA EYINGOZI, GALELA AMANZI ABANDAYO EMPOMPO KWINDAWO LEYO KWANGOKO IMIZUZU ELINESIHLANU KUXA KWENGAMASHUMI AMABINI. UNGAZE UXHOFE IZINCOBO EZINAMATHELEYO ELUSWINI OKANYE USEBENZISE I-OYILE NE-BUTTER, NGENXA YOKUBA ZIVALELA UBUSHUSHU NGAPHAKATHI ELUSWINI.",
        st: "EKABA KE HO TSUBELLA HO BAKOANG KE DINKHONO KAPA DIKHEMIKHALI TSE KOTSI, TSHELA METSI A BATANG A POMPO KAPELE METSOTSO E 10 HO ISA HO E 20. LE KA MOHLA O SE KE WA TLOOHA DIAPARO TSE MANAMATHETSENG LETLALONG KAPA WA SEBEDISA OLI KAPA MAFURA, HOBANE DI KWALLA MOFUTHU KA HAR'A NAMA."
      },
      {
        step: 6,
        title: "PATIENT RECOVERY LAYER",
        en: "IF THE CASUALTY IS UNCONSCIOUS BUT BREATHING NATIVELY, ROUTE THEM CAREFULLY INTO THE STABLE RECOVERY POSITION ON THEIR SIDE, ENSURING THE AIRWAY REMAINS UNBLOCKED AND CLEAR. LAY A REFLECTIVE FIRST AID FOIL BLANKET DIRECTLY OVER THE BODY TO REGULATE INTERNAL COMPLIANCE CORE TEMPERATURE AND MITIGATE NEUROLOGICAL TRAUMA SHOCK.",
        zu: "UMA ISIGULI SIQULEKILE KODWA SIPHEFU_ZELA KAHLE, BEKA ISIGULI NGOKUNYAKAZA OPHEPHILE ENDAWENI YOKULALELA (RECOVERY POSITION) NGECALA, UQINISEKISE UKUTHI INDLELA YOYA KHOYI IVULEKILE. MBEZA NGE-FOIL BLANKET YOKUSIZA LOKUQALA PHEZU KOMZIMBA UKUZE ULAOLE UKUSHISA NOMSINDO WESISHA SHOCK.",
        xh: "UKUBA ISIGULI SIQULEKILE KODWA SIPHEFUMLA KAHLE, BEKA ISIGULI NGOKUNYAKAZA OKUKHUSELEKILEYO KWINDAWO YOKULALELA (RECOVERY POSITION) NGECALA, UQINISEKISE UKUBA INDLELA YOYA KHOYI IVULEKILE. GQUMA NGE-FOIL BLANKET YONCEDO LOKUQALA PHEZUKOMZIMBA UKUZE ULAOLE UBUSHUSHU NOMSINDO WESIKHUMBA SHOCK.",
        st: "HAEBA MOKUDI A LIHEHILE EMPA A EFOMOLOHA HANTLE, MO BEHE KANGKONG EA RECOVERY POSITION KA LEHLAKORENG, HO NETEFATSA HORE TSELA YA MOYA E DULA E BULeHILE. BEHA REFLECTIVE FOIL BLANKET HODIMA MMELA HO LAOLA MOFUTHU WA MMELA MME O THIBELE SHOCK YA MALEBA."
      },
      {
        step: 7,
        title: "STATUTORY HANDOVER DOCUMENTATION",
        en: "MAINTAIN ABSOLUTE OVERSIGHT UNTIL EMERGENCY PARAMEDICS DEPLOY ON-SITE. HAND OVER THE SHIFT REGISTER DATA, COMPLETE AN OFFICIAL INCIDENT TRACKING FILE RECORD UNDER GENERAL SAFETY REGULATION 9 GUIDELINES, AND NOTIFY THE DESIGNATED SITE CHIEF HEALTH AND SAFETY REPRESENTATIVE IMMEDIATELY.",
        zu: "GCINA UKULAWULA OKUPHELELE KUZE KUFIKE ABASIZI BEZE_MPILO (PARAMEDICS). PHATHISA IDATHAYEREJISTA YESHIFU, GCWALISA IREKHODI LOMTHETHO LOMCIMBI NGAPHANSI KWEMITHETHO YE-GENERAL SAFETY REGULATION 9, BESE WAZISA UMPHATHI OPHEZULU WEZOKUPHEPHA (SHE REP) MASINYANE.",
        xh: "GCINA UKULAWULA OKUPHELELE KUZE KUFIKE ABASIZI BEZEMPILO (PARAMEDICS). PHATHISA IDATHA YEREJISTA YESHIFU, GCWALISA IREKHODI LOMTHETHO LOMCIMBI PHANTSI KWEMITHETHO YE-GENERAL SAFETY REGULATION 9, BESE WAZISA UMPHATHI OPHEZULU WEZOKUPHEPHA (SHE REP) KWANGOKO.",
        st: "DULA O LABALABELA HO FIHLELA LITSEBI TSA TSHOHANYETSO (PARAMEDICS) DI FIHLA. FANA KA DATA YA SHIFT REGISTER, QETELA REKHOTO YA SEMMUSO YA KOTSI TLAS'A MELAO YA GENERAL SAFETY REGULATION 9, MME O TSEBISE SHE REP YA SITE HANG-HANG."
      }
    ]
  },
  BASIC_FIRE_FIGHTING: {
    courseId: "ST-FF-002",
    title: "COURSE 2: BASIC FIRE FIGHTING AND EQUIPMENT HANDLING",
    steps: [
      {
        step: 1,
        title: "EMERGENCY ALARM ACTIVATION",
        en: "NOTIFY THE PERSON NEAREST TO THE EMERGENCY STOP BUTTON AND NOTIFY THE CASHIERS WHO IN TURN WILL ENSURE EVERYBODY THAT IS INSIDE THE BUILDING TO BE COUNTED FOR.",
        zu: "YAZISA UMUNTU OSUDEZE KAKHULU NENKINOBHO YE-EMERGENCY STOP MASINYANE, UPHINDE WAZISE ABASHAYELI BAMA-TILL (CASHIERS), BONA ABAZOWONELA UKUTHI WONKE UMUNTU ONGAPHAKATHI ESAKHIWENI UBALWA FUTHI UYALANDELEKA.",
        xh: "YAZISA UMNTU OKUFUTHANE KAKHULU NEQHOSHA LE-EMERGENCY STOP KWANGOKO, UZE WAZISE NABATHENGISI (CASHIERS), BONA ABAYA KUQINISEKISA UKUBA WONKE UMNTU ONGAPHAKATHI KWESAKHIWO UYABALWA KWAYE UYALANDELEKA.",
        st: "TSEBIŠA MOTHO YO A LEGO KGAUSWI LE KONOPO YA EMERGENCY STOP KAPELE MME O TSEBIŠE BA-CASHIER, KHO NA BA TLA NETEFATSA HORE MOTHO E MONG LE E MONG YA KA HAR'A MOAHO O A BALWA."
      },
      {
        step: 2,
        title: "PANIC CONTROL & MARSHALLING",
        en: "MANAGERS/MARSHALS TO MAKE SURE THERE IS NO PANIC, MANAGERS TO ENSURE EVERYONE INCLUDING CUSTOMERS INSIDE THE BUILDING TO FOLLOW THEM TOP THE RELEVANT ASSEMBLY POINT.",
        zu: "ABAPHATHI NAMA-MARSHALS KUFAN_ELE BAQINISEKISE UKUTHI AKUKHO UKUVALELISA NOKUPHAKUZELA, ABAPHATHI BAZOQINISEKISE UKUTHI WONKE AMAKHASIMENDE ANGAPHAKATHI ESAKHIWENI BAYABALANDELA BALISE EMAPHOYINTINI AFANELE OKUHLANGANA.",
        xh: "ABAPHATHI KUNYE NAMA-MARSHALS KUFUNEKA BAQINISEKISE UKUBA AKUKHO BHENDI NOKUPHAKUZELA, ABAPHATHI BAYA KUQINISEKISA UKUBA WONKE UMNTU QUQA NABATHENGI ABANGAPHAKATHI KWESAKHIWO BAYABALANDELA BAYE KWINDAWO EFANELEKILEYO YOKUHLANGANISANA.",
        st: "BAOKAMELI LE BA-MARSHAL BA TLAMEHA HO NETEFATSA HORE BA NA LE LETSHOGO LE HO PHAKUZELA, BAOKAMELI BA TLA NETEFATSA HORE MOTHO E MONG LE E MONG HO KENYELETSWA LE BAREKI BA KA HAR'A MOAHO BA BA LATELA HO YA NQALONG E KGETHEHILENG YA HO KOPANELA."
      },
      {
        step: 3,
        title: "SHIFT SHEET LOG RETENTION",
        en: "MANAGERS TO REMEMBER TO CARRY THE SHIFT SHEET FOR THAT PARTICULAR DAY TO USE AS ROLL CALL LIST AND UPDATE ACCORDINGLY.",
        zu: "ABAPHATHI MAKHUMB_ULE UKUPHATHA ISHIDI LESHIFU (SHIFT SHEET) LWALOLO SUKU OLUTH_ILE UKUZE NILISEBENZISE NJENGOHLU OLUSEMTH_EWENI LOKUBIZA AMAGAMA (ROLL CALL), NILUBUYEKEZE NGENDLELA EFANELE KHONA LAPHO.",
        xh: "ABAPHATHI MUKHUMBULE UKUPHATHA ISHIDI LESHIFU (SHIFT SHEET) LOLO SUKU LUTH_ILE UKUZE LILISEBENZISE NJENGOLUHLU OLUSEMTH_EWENI LOKBIZA AMAGAMA (ROLL CALL), NILUHLAZIYE NGENDLELA EFANELE KHONA LAPHO.",
        st: "BAOKAMELI LE HLE LE GOPOLE HO NKA SHIFT SHEET YA LETSATSI LEO LE KGETHEHILENG HO E SEBEDISA E LE LETHATHAMO LA SEMMUSO LA ROLL CALL, MME LE LE MPEFATSE HANTLE HANG-HANG."
      },
      {
        step: 4,
        title: "ACTIVE FIRE SUPPRESSION ACTION",
        en: "ALL STAFF THAT ARE TRAINED AND FEEL COMFORTABLE TO DO SO, WILL THEY RETRIEVE THE FIRE EXTINGUISHER AND PUT THE FIRE OFF AS PER TRAINING RECEIVED.",
        zu: "BONKE ABASEBENZI ABAQEQ_ESHIWE FUTHI ABAZIZWA BEKHUL_ULEKILE UKWENZA NJALO, BAZOTHATHA ISICISHAMLILO BASITSHELE UKUCISHA UMLILO NGOKOMQEQ_ESHO ABAWUTH_OLILE.",
        xh: "BONKE ABASEBENZI ABAQEQ_ESHIWEYO KWAYE BAZIVA BEKHUL_ULEKILE UKWENZA NJALO, BAYA KUTHATHA ISICINYAMLILO BASISEBENZISE UKUCIMA UMLILO NGOKUNXUL_UMENE NOQEQ_ESHO ABALUFU_MENEYO.",
        st: "BASEBETSI BOHLE BA KWETLISITSWENG MME BA IKUTLWANG BA PHUTHOLOHILE HO ETSA JALO, BA TLA NKA SETIMA-MOLLO MME BA TIME MOLLO KA TSELA EO BA KWETLISITSWENG KA YONA."
      },
      {
        step: 5,
        title: "FORECOURT TRAFFIC CONTAINMENT",
        en: "2X STAFF MEMBERS TO BLOCK OFF THE ENTRANCE AND EXITS OF THE SITE (CONTROLL TRAFFIC).",
        zu: "ABASEBENZI ABABILI (2X) KUFAN_ELE BAVIMBE IZINDAWO ZOKUNGENA NEZOKUPHUMA KULESI SIZA UKUZE BALAWULE ITHRAFIKHI NGENDLELA EFANELE.",
        xh: "ABASEBENZI ABABINI (2X) KUFUNEKA BAVIMBE IINDAWO ZOKUNGENA NEZOKUPHUMA KULE NDAWO UKUZE BALAWULE ITRAFIKHI NGENDLELA EFANELEKILEYO.",
        st: "BASEBETSI BA BABEDI (2X) BA TLAMEHA HO KWALA MENYAKO YA HO KENA LE HO TSWA YA SITE ENA HO LAOLA TRAFFIC KA BOTLALO."
      },
      {
        step: 6,
        title: "ENGINE SHUTDOWN & CLEARANCE SWEEPS",
        en: "OTHER FORECOURT STAFF TO ADVICE THE CUSTOMERS TO SWITCH THEIR ENGINES OFF TO FOLLOW THEM TO THE RELEVANT ASSEMBLY POINT, WILL ALSO ENSURE ALL THE RESTROOMS AND KIOSK IS CHECKED FOR STAFF OR CUSTOMERS (WE NEED TO ACCOUNT FOR EVERYONE THAT'S ON SGIFT THAT DAY INCLUDING CUSTOMERS.",
        zu: "ABANYE ABASEBENZI BASENK_UNDLENI (FORECOURT STAFF) KUFAN_ELE BACEBISE AMAKHAS_IMENDE UKUTHI ACISHE IZINJ_INI ZAWO, BAWAL_ANDELE BEYE ENDAWENI EFANELE YOKUHL_ANGANA, BAQIN_ISEKISE UKUTHI WONKE AMAGUMBI OKUPH_UMULA (RESTROOMS) KANYE NE-KIOSK KUYAHL_OLWA UKUTHI ABEKHO YINI ABASEBENZI NOMA AMAKHAS_IMENDE ASELE UKUZE KUBALWA WONKE UMUNTU OSESH_IFINI NGALELO SUKU KUHLANGAN_ISE NAMAKHAS_IMENDE.",
        xh: "ABANYE ABASEBENZI BASEBALENI (FORECOURT STAFF) KUFUNEKA BACEBISE ABATHENGI UKUBA BACIME IINJ_INI ZABO, BABAL_ANDELE BAYE KWINDAWO EFANELEKILEYO YOKUHL_ANGANISANA, BAQIN_ISEKISE UKUBA ONKE AMAGUMBI OKUPH_UMULA (RESTROOMS) KUNYE NE-KIOSK IYAHL_OLWA UKUTHI AKUKHO BASEBENZI OKANYE BATHENGI BASALE_LEYO UKUZE KUBALWA WONKE UMNTU OSESH_IFINI NGALO MINI.",
        st: "BASEBETSI BA BANG BA FORECOURT BA TLAMEHA HO ELETSA BAREKI HO TIMA DINKHONO (ENGINES) TSA BONA MME BA BA HANELE HO YA NQALONG E KGETHEHILENG YA HO KOPANELA, MME BA NETEFATSE HORE MATLO A BOIKH_UTSO (RESTROOMS) LE KIOSK DI HLAHLO_BJWA KA BOTLALO HO BONA HORE NA HO NA LE MOSEBETSIKAPA MOREKI YA SETSENG UKUZE HO BALWE MOTHO E MONG LE E MONG YA LENG TENG SHIFT_ENG LETSATS_ING LEO."
      },
      {
        step: 7,
        title: "EMERGENCY COMMUNICATIONS MAINTENANCE",
        en: "MANAGERS AND MARSHALS TO ENSURE THEY HAVE THE EMERGENCY TEL NO'S.",
        zu: "ABAPHATHI NAMA-MARSHALS KUFAN_ELE BAQIN_ISEKISE UKUTHI BANEZIN_OMBOLO ZOCINGO EZIPH_UTHUMAYO (EMERGENCY TEL NO'S) NGASO SONKE ISIKH_ATHI.",
        xh: "ABAPHATHI KUNYE NAMA-MARSHALS KUFUNEKA BAQIN_ISEKISE UKUBA BANEEN_OMBOLO ZOMNX_EBA ZONGX_AMISEKO (EMERGENCY TEL NO'S) NGAMAX_ESHA ONKE.",
        st: "BAOKAMELI LE BA-MARSHAL BA TLAMEHA HO NETEFATSA HORE BA NA LE DINOMB_OLO TSA MOHALA TSA TSHOH_ANYETSO (EMERGENCY TEL NO'S) KA DINAKO TSOHLE."
      }
    ]
  },
  EMERGENCY_SPILL: {
    courseId: "ST-SR-003",
    title: "COURSE 3: EMERGENCY SPILL RESPONSE TRAINING",
    steps: [
      {
        step: 1,
        title: "EMERGENCY SHUTOFF ISOLATION",
        en: "NOTIFY THE PERSON NEAREST TO THE EMERGENCY STOP BUTTON AND NOTIFY THE CASHIERS WHO IN TURN WILL ENSURE EVERYBODY THAT IS INSIDE THE BUILDING TO BE COUNTED FOR.",
        zu: "YAZISA UMUNTU OSUDEZE KAKHULU NENKINOBHO YE-EMERGENCY STOP MASINYANE, UPHINDE WAZISE ABASHAYELI BAMA-TILL (CASHIERS), BONA ABAZOWONELA UKUTHI WONKE UMUNTU ONGAPHAKATHI ESAKHIWENI UBALWA FUTHI UYALANDELEKA.",
        xh: "YAZISA UMNTU OKUFUTHANE KAKHULU NEQHOSHA LE-EMERGENCY STOP KWANGOKO, UZE WAZISE NABATHENGISI (CASHIERS), BONA ABAYA KUQINISEKISA UKUBA WONKE UMNTU ONGAPHAKATHI KWESAKHIWO UYABALWA KWAYE UYALANDELEKA.",
        st: "TSEBIŠA MOTHO YO A LEGO KGAUSWI LE KONOPO YA EMERGENCY STOP KAPELE MME O TSEBIŠE BA-CASHIER, KHO NA BA TLA NETEFATSA HORE MOTHO E MONG LE E MONG YA KA HAR'A MOAHO O A BALWA."
      },
      {
        step: 2,
        title: "VAPOR EGRESS & CUSTOMER MARSHALLING",
        en: "MANAGERS/MARSHALS TO MAKE SURE THERE IS NO PANIC, MANAGERS TO ENSURE EVERYONE INCLUDING CUSTOMERS INSIDE THE BUILDING TO FOLLOW THEM TOP THE RELEVANT ASSEMBLY POINT KUDE NENDAWO ENOMHWAMUKO KAPHETHILOLI.",
        zu: "ABAPHATHI NAMA-MARSHALS KUFAN_ELE BAQINISEKISE UKUTHI AKUKHO UKUVALELISA NOKUPHAKUZELA, ABAPHATHI BAZOQINISEKISE UKUTHI WONKE UMUNTU KUHLANGAN_ISE NAMAKHASIMENDE ANGAPHAKATHI ESAKHIWENI BAYABALANDELA BALISE EMAPHOYINTINI AFANELE OKUHLANGANA KUDE NENDAWO ENOMHWAMUKO KAPHETHILOLI.",
        xh: "ABAPHATHI KUNYE NAMA-MARSHALS KUFUNEKA BAQINISEKISE UKUBA AKUKHO BHENDI NOKUPHAKUZELA, ABAPHATHI BAYA KUQINISEKISA UKUBA WONKE UMNTU QUQA NABATHENGI ABANGAPHAKATHI KWESAKHIWO BAYABALANDELA BAYE KWINDAWO EFANELEKILEYO YOKUHLANGANISANA KUDE NDAWO ENOMPHUNGA.",
        st: "BAOKAMELI LE BA-MARSHAL BA TLAMEHA HO NETEFATSA HORE BA NA LE LETSHOGO LE HO PHAKUZELA, BAOKAMELI BA TLA NETEFATSA HORE MOTHO E MONG LE E MONG HO KENYELETSWA LE BAREKI BA KA HAR'A MOAHO BA BA LATELA HO YA NQALONG E KGETHEHILENG YA HO KOPANELA."
      },
      {
        step: 3,
        title: "SHIFT LOG ATTENDANCE CAPTURE",
        en: "MANAGERS TO REMEMBER TO CARRY THE SHIFT SHEET FOR THAT PARTICULAR DAY TO USE AS ROLL CALL LIST AND UPDATE ACCORDINGLY.",
        zu: "ABAPHATHI MAKHUMB_ULE UKUPHATHA ISHIDI LESHIFU (SHIFT SHEET) LWALOLO SUKU OLUTH_ILE UKUZE NILISEBENZISE NJENGOHLU OLUSEMTH_EWENI LOKUBIZA AMAGAMA (ROLL CALL), NILUBUYEKEZE NGENDLELA EFANTE KHONA LAPHO.",
        xh: "ABAPHATHI MUKHUMBULE UKUPHATHA ISHIDI LESHIFU (SHIFT SHEET) LOLO SUKU LUTH_ILE UKUZE LILISEBENZISE NJENGOLUHLU OLUSEMTH_EWENI LOKBIZA AMAGAMA (ROLL CALL), NILUHLAZIYE NGENDLELA EFANELE KHONA LAPHO.",
        st: "BAOKAMELI LE HLE LE GOPOLE HO NKA SHIFT SHEET YA LETSATSI LEO LE KGETHEHILENG HO E SEBEDISA E LE LETHATHAMO LA SEMMUSO LA ROLL CALL, MME LE LE MPEFATSE HANTLE HANG-HANG."
      },
      {
        step: 4,
        title: "SPILL ISOLATION & ABSORBENT APPLICATION",
        en: "ALL STAFF THAT ARE TRAINED AND FEEL COMFORTABLE TO DO SO, WILL THEY RETRIEVE THE CHEMICAL SPILL KIT AND DEPLOY ABSORBENT GRANULES OR SAND TO PUT THE FUEL MIGRATION OFF AS PER TRAINING RECEIVED.",
        zu: "BONKE ABASEBENZI ABAQEQESHIWE FUTHI ABAZIZWA BEKHULULEKILE UKWENZA NJALO, BAZOTHATHA IKHITHI YOKUHLANZA AMAKHEMIKHALI (SPILL KIT) BASEBENZISE AMA-ABSORBENT GRANULES NOMA ISIHLABATHI UKUVIMBELA UKUHAMBA KUKAPHETHILOLI NGOKOMQEQESHO ABAWUTHOLILE.",
        xh: "BONKE ABASEBENZI ABAQEQESHIWEYO KWAYE BAZIVA BEKHULULEKILE UKWENZA NJALO, BAYA KUTHATHA ISIXHOBO SOKUCOCA IMICHIZA (SPILL KIT) BASEBENZISE AMA-ABSORBENT GRANULES OKANYE ISANTI UKUTHINTELA UKUHAMBA KOLWELO NGOKUNXULUMENE NOQEQESHO ABALUFUMENEYO.",
        st: "BASEBETSI BOHLE BA KWETLISITSWENG MME BA IKUTLWANG BA PHUTHOLOHILE HO ETSA JALO, BA TLA NKA SPILL KIT MME BA SEBEDISE DI-ABSORBENT GRANULES KAPA LEHLABATHE HO THIBELA HORE MAFURA A SE KE AYA HOHLE KA TSELA EO BA KWETLISITSWENG KA YONA."
      },
      {
        step: 5,
        title: "VEHICLE ENTRY PREVENTION",
        en: "2X STAFF MEMBERS TO BLOCK OFF THE ENTRANCE AND EXITS OF THE SITE (CONTROLL TRAFFIC).",
        zu: "ABASEBENZI ABABILI (2X) KUFAN_ELE BAVIMBE IZINDAWO ZOKUNGENA NEZOKUPHUMA KULESI SIZA UKUZE BALAWULE ITHRAFIKHI NGENDLELA EFANELE FUTHI BAVIMBE IZINJINI EZISHISAYO EDUZE KUKAPHETHILOLI OWANDAYO.",
        xh: "ABASEBENZI ABABINI (2X) KUFUNEKA BAVIMBE IINDAWO ZOKUNGENA NEZOKUPHUMA KULE NDAWO UKUZE BALAWULE ITRAFIKHI NGENDLELA EFANELEKILEYO THINTELA IZITHUTHI EZINEENJINI EZISHISAYO.",
        st: "BASEBETSI BA BABEDI (2X) BA TLAMEHA HO KWALA MENYAKO YA HO KENA LE HO TSWA YA SITE ENA HO LAOLA TRAFFIC KA BOTLALO LE HO THIBELA DIKOLOI TSE NANG LE DINKHONO TSE CHESANG."
      },
      {
        step: 6,
        title: "IGNITION SUPPRESSION & CLEARANCE SWEEPS",
        en: "OTHER FORECOURT STAFF TO ADVICE THE CUSTOMERS TO SWITCH THEIR ENGINES OFF TO FOLLOW THEM TO THE RELEVANT ASSEMBLY POINT, WILL ALSO ENSURE ALL THE RESTROOMS AND KIOSK IS CHECKED FOR STAFF OR CUSTOMERS (WE NEED TO ACCOUNT FOR EVERYONE THAT'S ON SGIFT THAT DAY INCLUDING CUSTOMERS.",
        zu: "ABANYE ABASEBENZI BASENK_UNDLENI KUFAN_ELE BACEBISE AMAKHAS_IMENDE UKUTHI ACISHE IZINJ_INI ZAWO NGOKUSHESHA UKUZE KUBULAWE YONKE IMITHOMBO YOMLILO, BAWAL_ANDELE BEYE ENDAWENI EFANELE YOKUHL_ANGANA, BAQIN_ISEKISE UKUTHI WONKE AMAGUMBI OKUPH_UMULA KANYE NE-KIOSK KUYAHL_OLWA UKUTHI ABEKHO YINI ABASEBENZI NOMA AMAKHAS_IMENDE ASELE UKUZE KUBALWA WONKE UMUNTU OSESH_IFINI NGALELO SUKU.",
        xh: "ABANYE ABASEBENZI BASEBALENI KUFUNEKA BACEBISE ABATHENGI UKUBA BACIME IINJ_INI ZABO KWANGOKO UKUTHINTELA IMITHOMBO YOMLILO, BABAL_ANDELE BAYE KWINDAWO EFANELEKILEYO YOKUHL_ANGANISANA, BAQIN_ISEKISE UKUBA ONKE AMAGUMBI OKUPH_UMULA KUNYE NE-KIOSK IYAHL_OLWA UKUTHI AKUKHO BASEBENZI OKANYE BATHENGI BASALE_LEYO UKUZE KUBALWA WONKE UMNTU OSESH_IFINI NGALO MINI.",
        st: "BASEBETSI BA BANG BA FORECOURT BA TLAMEHA HO ELETSA BAREKI HO TIMA DINKHONO TSA BONA KAPELE HO TIMA MOHLOLI OFE KAPA OFE WA MOLLO, MME BA BA HANELE HO YA NQALONG E KGETHEHILENG YA HO KOPANELA, MME BA NETEFATSE HORE MATLO A BOIKH_UTSO LE KIOSK DI HLAHLO_BJWA UKUZE HO BALWE MOTHO E MONG LE E MONG LETSATS_ING LEO."
      },
      {
        step: 7,
        title: "EMERGENCY DISPATCH ACCESS",
        en: "MANAGERS AND MARSHALS TO ENSURE THEY HAVE THE EMERGENCY TEL NO'S.",
        zu: "ABAPHATHI NAMA-MARSHALS KUFAN_ELE BAQIN_ISEKISE UKUTHI BANEZIN_OMBOLO ZOCINGO ZEZIMO EZIPH_UTHUMAYO ZAMAKHEMIKHALI NEZICISHAMLILO NGASO SONKE ISIKH_ATHI.",
        xh: "ABAPHATHI KUNYE NAMA-MARSHALS KUFUNEKA BAQIN_ISEKISE UKUBA BANEEN_OMBOLO ZOMNX_EBA ZESHU LOMLILO KUNYE NEENGX_AMISEKO NGAMAX_ESHA ONKE.",
        st: "BAOKAMELI LE BA-MARSHAL BA TLAMEHA HO NETEFATSA HORE BA NA LE DINOMB_OLO TSA MOHALA TSA LITSHEBELETSO TSA TIMA-MOLLO LE TSHOH_ANYETSO KA DINAKO TSOHLE."
      }
    ]
  }
};
